discussion/urls.py
from django.urls import path
from .views import discussion, discussionPost, discussionGet


app_name = 'discussion'

urlpatterns = [
    path('', discussion, name='discussion'),
    path('postdata/', discussionPost),
    path('getdata/', discussionGet),
]

feedback/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'feedback'

urlpatterns = [
    path("", views.create, name="feedback"),
    path('masukan_data/',views.masukan_data),
    path('get_data/',views.get_data),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mathemagic/urls.py
from django.urls import path, include
from django.contrib import admin
import mathgame.views
import discussion.views
import namelogin.views
import feedback.views

app_name = 'namelogin', 'mathgame', 'discussion', 'feedback'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feedback/', include('feedback.urls')),
    path('mathgame/', mathgame.views.index, name='mathgame'),
    path('mathgame/postdata/', mathgame.views.postdata, name='postdata'),
    path('discussion/', include('discussion.urls')),
    path('', namelogin.views.homepage, name= 'landing-page'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', namelogin.views.SignUp.as_view(), name='signup'),
    path('get_data/', namelogin.views.get_data, name="get_data"),
]

discussion/models.py
from django.db import models
from django.utils import timezone


class discussionModels (models.Model):
    name = models.CharField(max_length = 10)
    discussion = models.CharField(max_length = 500)
    time = models.DateTimeField(default = timezone.now)

discussion/forms.py
from django import forms
from .models import discussionModels


class discussionForms(forms.Form):
    name = forms.CharField(label='Your Name', max_length=10,
        widget=forms.TextInput(attrs={'class' : 'form-control marginbottom10', 'placeholder' : 'Max 20 character'}))

    discussion = forms.CharField(label='Discussion', max_length=500,
        widget=forms.TextInput(attrs={'class' : 'form-control marginbottom10 heightDiscussion', 'placeholder' : 'Tell us what you think'}))
    

discussion/views.py
from django.shortcuts import render
from .forms import discussionForms
from .models import discussionModels
from django.utils import timezone
from django.core import serializers
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

import json
import requests


def discussion(request):
    form = discussionForms()
    return render(request, 'discussion/discussion.html', {'form': form})

@csrf_exempt
def discussionPost(request):
    if request.method == "POST":
        form = discussionForms(request.POST)
        discussion = request.POST['discussion']
        name = request.POST['name']
        print("masuk if")
        model = discussionModels(discussion=discussion, name=name)
        model.save()

        discussion = list(discussionModels.objects.order_by('-time').values('discussion'))
        name = list(discussionModels.objects.order_by('-time').values('name'))
        time = list(discussionModels.objects.order_by('-time').values('time'))
        return JsonResponse({'discussionList': discussion, 'nameList': name, 'timeList': time})

def discussionGet(request):
    if request.method == "GET":
        discussion = list(discussionModels.objects.order_by('-time').values('discussion'))
        name = list(discussionModels.objects.order_by('-time').values('name'))
        time = list(discussionModels.objects.order_by('-time').values('time'))
        return JsonResponse({'discussionList': discussion, 'nameList': name, 'timeList': time})

discussion/templates/discussion/discussion.html
{% extends 'base.html' %}
{% load static %}

{% block additionalHeaders%}
    <link href="{% static 'css/discussion.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Coming+Soon|Fredoka+One&display=swap" rel="stylesheet">
{% endblock additionalHeaders%}


{% block content %}
<style>
html, body{
    height: 100%;
}
</style>
<div class="container-fluid bg">
    <h1 class = "discussion">DISCUSSION</h1>

        <div class="row">
            <div class="col-sm-3" style="margin-left: 20px; margin-top: 50px;">
                {% if user.is_authenticated %}

                <h5>Hello <strong>{{ user.username }}</strong>, what do you want to discuss?</h5>
                <input type="hidden" value="{{ user.username }}" name="name" class="form-control marginbottom10" placeholder="Max 20 character" maxlength="10" required="" id="id_name">
                <input type="text" name="discussion" class="form-control marginbottom10 heightDiscussion" placeholder="Tell us what you think" maxlength="500" required="" id="id_discussion">
                <div class="sign-in"> <a href="{% url 'logout' %}">Log out</a></div>
                {% else %}

                {% csrf_token %}
                {{ form }}
                <div class="sign-in"> <a href="{% url 'login' %}">Log in</a></div>
                <div class = "sign-up">Don't have an account? <a href="{% url 'signup' %}"> Sign up!</a></div>
                
                {% endif %}
                
                <br>
                <input id="id_post" type="submit" value="POST!" style="margin-bottom: 50px;">
            </div>
            <div class="col-sm-8 discussionTable">
                <div id="id_table" class="container row" style="overflow: auto; height: 75vh;">
                </div>
            </div>
        </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    $("#id_post").on('click',
        function () {
            var name = $("#id_name").val();
            var discussion = $("#id_discussion").val();
            if (name == "" || discussion == "") {
                alert("Please Fill All Required Field");
                return;
            }
            $.ajax({
                type: "POST",
                url : "/discussion/postdata/",
                data: {
                    'name' : name,
                    'discussion' : discussion,
                    'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val(),
                },
                success: function(result){
                    alert("Post Successfully create!!")
                    $("#id_discussion").val("");
                    $("#id_name").val("");
                    $("#id_table").prepend(
                        '<div class="col-sm-6 col-md-6 name_and_date">' + 
                            '<b>' + result.nameList[0].name + '</b>'+
                        '</div>' +  
                        '<div class="col-sm-6 col-md-6 name_and_date" style="color: gray; text-align: left;">'+
                            result.timeList[0].time+
                        '</div>'+
                        '<div class="col-sm-12">'+
                            result.discussionList[0].discussion+
                            '<hr size="20">'+
                        '</div>'
                    );
                }
            })
        }
    )
    
    $("document").ready(
    function getDiscussionData() {
        $.ajax({
            type : "GET",
            url : "/discussion/getdata/",
            dataType : "json",
            success : function (result) {

                var jumlah = result.discussionList.length
                var discussionList = result.discussionList
                var nameList = result.nameList
                var timeList = result.timeList
                $("#id_table").empty();
                for (let index = 0; index < jumlah; index++) {
                    $("#id_table").append(
                        '<div class="col-sm-6 col-md-6 name_and_date">' + 
                            '<b>' + nameList[index].name + '</b>'+
                        '</div>' + 
                        '<div class="col-sm-6 col-md-6 name_and_date" style="color: gray; text-align: left;">'+
                            timeList[index].time+
                        '</div>'+
                        '<div class="col-sm-12">'+
                            discussionList[index].discussion+
                            '<hr size="20">'+
                        '</div>'
                    );
                }
                
                setTimeout(function() {
                    getDiscussionData();
                }, 15000);    
            }
        })
    }
    )

    $("#id_name").keypress(
    function nameTest() {
        var name = $("#id_name").val();
        if (name.length > 10) {
            alert("Max name: 10 character");
            return;
        }
    }
    )

    $("#id_discussion").keypress(
    function discussionTest() {
        var name = $("#id_discussion").val();
        if (name.length > 200) {
            alert("Max post: 200 character");
            return;
        }
    }
)


</script>
{% endblock content %}