discussion/urls.py
from django.urls import path
from .views import discussion, discussionPost, discussionGet


app_name = 'discussion'

urlpatterns = [
    path('', discussion, name='discussion'),
    path('postdata/', discussionPost),
    path('getdata/', discussionGet),
]

feedback/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'feedback'

urlpatterns = [
    path("", views.create, name="feedback"),
    path('masukan_data/',views.masukan_data),
    path('get_data/',views.get_data),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mathemagic/urls.py
from django.urls import path, include
from django.contrib import admin
import mathgame.views
import discussion.views
import namelogin.views
import feedback.views

app_name = 'namelogin', 'mathgame', 'discussion', 'feedback'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feedback/', include('feedback.urls')),
    path('mathgame/', mathgame.views.index, name='mathgame'),
    path('mathgame/postdata/', mathgame.views.postdata, name='postdata'),
    path('discussion/', include('discussion.urls')),
    path('', namelogin.views.homepage, name= 'landing-page'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', namelogin.views.SignUp.as_view(), name='signup'),
    path('get_data/', namelogin.views.get_data, name="get_data"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mathe Magic!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://necolas.github.io/normalize.css/latest/normalize.css"
      rel="stylesheet"
    />
    <style>
        .navbar {
            background-color: transparent !important;
        }
        .logo-wrapper {
            width: 50px;
            height: 50px;
            object-fit: contain;
        }
    </style>
    {% block additionalHeaders %}

    {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'mathgame' %}"><img class="logo-wrapper" src= "https://files.catbox.moe/9scbd9.png"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'landing-page' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Join Us!</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'discussion:discussion' %}">Discussion Room</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'feedback:feedback' %}">Any Problem?</a>
            </li>
        </ul>
    </div>
</nav>
{% block content %}

{% endblock %}
</body>
</html>