feedback/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'feedback'

urlpatterns = [
    path("", views.create, name="feedback"),
    path('masukan_data/',views.masukan_data),
    path('get_data/',views.get_data),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mathemagic/urls.py
from django.urls import path, include
from django.contrib import admin
import mathgame.views
import discussion.views
import namelogin.views
import feedback.views

app_name = 'namelogin', 'mathgame', 'discussion', 'feedback'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feedback/', include('feedback.urls')),
    path('mathgame/', mathgame.views.index, name='mathgame'),
    path('mathgame/postdata/', mathgame.views.postdata, name='postdata'),
    path('discussion/', include('discussion.urls')),
    path('', namelogin.views.homepage, name= 'landing-page'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', namelogin.views.SignUp.as_view(), name='signup'),
    path('get_data/', namelogin.views.get_data, name="get_data"),
]

feedback/models.py
from django.db import models

# Create your models here.
class PostModel(models.Model):
    name    = models.CharField(max_length=30)
    message = models.CharField(max_length=250)

feedback/forms.py
from django import forms
from .models import PostModel

class PostForm(forms.ModelForm):

    name = forms.CharField(widget=forms.TextInput(
        attrs= {
            'class': 'form-control',
            'placeholder': 'tell us, what is your name?',
            'size': '65%,',
        }
    ))

    message = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'let MatheMagic knows that ...',
        }
    ))

    class Meta:
        model = PostModel
        fields = [
            'name',
            'message',
        ]

feedback/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponse,JsonResponse

# Create your views here.
from .forms import PostForm
from .models import PostModel

def show(request):
    posts = PostModel.objects.all()

    context = {
        'posts':posts,
    }

    return render(request, 'feedback/feedback-content.html', context)

def create(request):
    post_form = PostForm(request.POST or None)
    if request.method == 'POST':  # POST request from browser
        if post_form.is_valid():
            post_form.save()
            return render(request, 'feedback/feedback.html')

    context = {
        'post_form': post_form,
    }

    return render(request, 'feedback/feedback.html', context)

def masukan_data(request):
    response_data = {}
    if request.method == "POST":
        if (request.user.is_authenticated):
            name = request.user.username
        else:
            name = request.POST['name']
        message = request.POST['message']
        model = PostModel(name= name,
                          message= message)
        model.save()
        response_data['name'] = name
        print(name)
    response_data['banyakData'] = PostModel.objects.all().count()
    return JsonResponse(response_data)

def get_data(request):
    name_list = list(PostModel.objects.values('name'))
    count = len(name_list)
    return JsonResponse({'banyakNama':count , 'name':name_list})

feedback/templates/feedback/feedback-content.html
{% extends 'base.html' %}
{% load static %}

{% block additionalHeaders %}
    <link href="{% static 'feedback/css/feedback.css' %}" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Coming+Soon|Fredoka+One&display=swap" rel="stylesheet">
{% endblock additionalHeaders %}

{% block content %}
    <div class="section-body">
        <h2 class="title-feedback">User's Feedback for MatheMagic!</h2>
        <table style="width: 80%">
            <tr>
                <th>Name</th>
                <th>Message</th>
            </tr>
            {% for post in posts %}
                <tr>
                    <td>{{ post.name }}</td>
                    <td>{{ post.message }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}

feedback/templates/feedback/feedback.html
{% extends 'base.html' %}
{% load static %}

{% block additionalHeaders %}
    <link href="{% static 'feedback/css/feedback.css' %}" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Coming+Soon|Fredoka+One&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'feedback/js/feedback.js' %}"></script>
{% endblock additionalHeaders%}

{% block content %}
<div class="section-body, light">
    <label id="circle" class="circle">🌓</label>
    {% csrf_token %}
    {% if user.is_authenticated %}
        <h2 class="title-feedback">Leave your thought here {{ user.username }}!</h2>
    {% else %}
         <h2 class="title-feedback">Leave your thought here!</h2>
    {% endif %}
    <div class="section-image">
        <img
                src="https://pngimage.net/wp-content/uploads/2018/05/confused-girl-png-8.png"
                alt="questioning-girl"
                class="section-image"
        />
    </div>
        {% csrf_token %}
        <table>
            <tr>
                {{ post_form.as_table }}
            </tr>
        </table>
         <br/>
    <button class="btn btn-warning btn-sm btn-block" style="align-self: center" id="id_button">Send!</button>
    <br/>
        <h4 id="ubah"></h4>
    <br/>
    <div class="messages">
        {% if messages %}
            <div>
            {% for message in messages %}
                <h5{% if message.tags %} class="message.tags" {% endif %}> {{ message }} </h5>
            {% endfor %}
            </div>
        {% endif %}
    </div>
</div>
    <script src="{% static 'feedback/js/feedback.js' %}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    $("#id_button").on('click',
    function () {
        var nameInput = $("#id_name").val();
        var messageInput = $("#id_message").val();
                console.log(nameInput)
                        console.log(messageInput)
        $.ajax({
            type: "POST",
            url : "/feedback/masukan_data/",
            data: {
                'name' : nameInput,
                'message' : messageInput,
                'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val(),
            },
            success: function(result){
                alert("Your message successfully posted, " + result.name + "!")
                $("#id_name").val("");
                $("#ubah").empty();
                var value = result.banyakData + " math lovers have sent us messages"
                $("#ubah").append(value);
            }
        })
    }
)

</script>
{% endblock content %}